name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Switch to gh-pages branch
        run: |
          git checkout gh-pages
          git merge main

      - name: Push changes to gh-pages
        run: |
          git push origin gh-pages
